### ISSUE TITLE
Not able to add additional languages

### ISSUE THREAD

**Issue by raminos** [andrewbranch/gatsby-remark-vscode#129]
Thanks for this fantastic plugin. I'm completely in love with it.

Lately I started to experiment with VimScript and therefore wanted to add a blogpost. Sadly, I'm not able to get the syntax highlighting to work. 

When I try to install a vscode syntax highlighting project like https://github.com/dunstontc/viml with npm I get an error because it can't find vscode:

```
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! viml@0.1.7 postinstall: `node ./node_modules/vscode/bin/install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the viml@0.1.7 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

I think I'm probably missing something 😅 . What would be the recommended way to install another language?

**Comment by andrewbranch** [comment]
You’re not missing something, the language author is! For some reason a bad practice of using a `postinstall` instead of a `prepare` script seems to have circulated widely around these VS Code extensions. I’ve fixed a number of them myself already. I don’t have time to fix this one myself at the moment, but you can do it by replicating [this one](https://github.com/juanfranblanco/vscode-solidity/pull/186) on the viml repo.

**Comment by raminos** [comment]
Awesome! Thanks Andrew. Will try to tackle this on a calm evening this week. 🎉
