### ISSUE TITLE
GraphQL error: Cannot read property 'path' of undefined

### ISSUE THREAD

**Issue by janosh** [andrewbranch/gatsby-remark-vscode#14]
Really cool plugin! Thanks for the excellent documentation. Love the [Why gatsby-remark-vscode?](https://github.com/andrewbranch/gatsby-remark-vscode#why-gatsby-remark-vscode) section.

Just trying it out as a drop-in replacement for `gatsby-remark-prismjs` gave me a bunch of errors of the sort
```sh
The GraphQL query from ./src/templates/post.js failed.
Errors:
  Cannot read property 'path' of undefined
  
  GraphQL request (26:3)
  25:   }
  26:   timeToRead
           ^
  27:   excerpt(pruneLength: 200)
```
Sounds like `gatsby-remark-vscode` isn't getting along with `gatsby-transformer-remark`. Any ideas what might be causing this?

Also, it would be nice to explicitly list available `languageAliases` in the readme. I assume any of the 55 built-in languages can be used as the alias target but it'd still be good to know the exact names the use there. For instance, should I write 
```
options: {
  languageAliases: { env: `sh` }, \\ is it `sh` or `shell` or `bash`
}
```

**Comment by andrewbranch** [comment]
Hm, unfortunately Gatsby is somehow obscuring the real error here. Is your project open source by any chance? I'd be happy to investigate with your codebase and see if I can better ensure real errors get surfaced correctly.

Totally agree on the language aliases. They're not written down because they're determined automatically from VS Code’s built-in extensions, but I forgot to detail how that works. I also need to check if an alias that resolves to another alias will work—I'm not sure off the top of my head, but that's something I'd like to support, which would mean that `sh`, `shell`, or `bash` would all work perfectly fine there.

**Comment by janosh** [comment]
Thanks for offering to help! The project I was referring to is [my personal site](https://github.com/janosh/janosh.io).

**Comment by andrewbranch** [comment]
Could you give v1.0.3 a shot? This should be fixed now, and I also added [a note about how language codes are resolved](https://github.com/andrewbranch/gatsby-remark-vscode#languages). To answer your specific question, you could make an alias from `env` to any of these:

      "shellscript",
      "bash",
      "sh",
      "zsh",
      "ksh",
      "bashrc",
      "bash_aliases",
      "bash_profile",
      "bash_login",
      "ebuild",
      "install",
      "profile",
      "bash_logout",
      "zshrc",
      "zprofile",
      "zlogin",
      "zlogout",
      "zshenv",
      "zsh-theme"

I'm gonna go ahead and close this out. Thanks for giving this a try and reporting the bug!

**Comment by janosh** [comment]
Fix confirmed. Works great now! Thanks for the quick response.
