### ISSUE TITLE
Weird colors in Safari

### ISSUE THREAD

**Issue by janosh** [andrewbranch/gatsby-remark-vscode#16]
With #14 resolved, the rest of the process of replacing `gatsby-remark-prismjs` with `gatsby-remark-vscode` was really smooth! Syntax highlighting with `gatsby-remark-vscode` takes much less configuration! It even fixed an annoying problem I had with the background of highlighted lines not extending beyond the initial viewport, i.e. being cutoff on narrow screens when scrolling to the right.

![highlighted-lines-cutoff](https://user-images.githubusercontent.com/30958850/57193061-43041d80-6f2f-11e9-8894-b8989266f565.png)

Thanks for providing this great addition to Gatsby's plugin ecosystem!

I deployed a [test version of my site](https://5ccec12eb98081a1fc79a6f4--janosh.netlify.com/blog/js-media-queries) after the swap `gatsby-remark-prismjs` -> `gatsby-remark-vscode`. Everything looks great in Chrome and Firefox but for some reason, the colors are very different in Safari. For example, tokens like brackets, `=`, etc. are black in Safari and hence invisible on a dark background

![safari-colors](https://user-images.githubusercontent.com/30958850/57193161-5d8ac680-6f30-11e9-97cb-cc26753b90fb.png)

whereas they are white in Chrome and Firefox.

![chrome-colors](https://user-images.githubusercontent.com/30958850/57193166-61b6e400-6f30-11e9-840c-e9b625774ef6.png)

Any ideas what might be causing this?

**Comment by andrewbranch** [comment]
It looks like you're including this CSS somehow (I think through a CSS-in-JS library):

```css
pre.vscode-highlight {
    position: relative;
    background: rgb(5, 4, 49);
    border-radius: 0.5em;
}
```

but you’re also using `prefersLight: 'light-default-light'`. The default light theme you're including there has a white background, but you're setting a dark background regardless of the prefers-color-scheme media query. I should update the README to specify that you probably _don't_ want to set all three of default, light, and dark themes, because up-to-date macOS users are either going to have a preference of `dark` or `light`—they'll never hit the default if you provide a prefers-light _and_ a prefers-dark.

I think the media query was designed to support a future where color scheme preferences are more rich and granular than just light/dark, e.g. being able to respond to a preference for an accessible high-contrast theme. But today it's pretty much just a light/dark preference or unsupported.

I would recommend using the `replaceColor` option rather than a CSS override to set that background color, and/or revisiting your color theme settings to ensure they actually match your intention.

(/cc @smockle if he’s interested in chiming in—he’s done much more extensive research on this than I have.)

**Comment by janosh** [comment]
Ah, yes that makes perfect sense. Should have thought about this more carefully.

Using `replaceColor` seems a little bit like a fragile solution.

```js
{
  resolve: `gatsby-remark-vscode`,
  options: {
    colorTheme: `Dark+ (default dark)`,
    replaceColor: oldColor =>
      ({
        '#ff0000': `var(--red)`,
        '#00ff00': `var(--green)`,
        '#0000ff': `var(--blue)`,
      }[oldColor.toLowerCase()] || oldColor),
  },
},
```

Wouldn't `replaceColor` require me to change the keys of the colors object every time I change the `colorTheme`? It might be more elaborate to set up but also more robust to have some semantic mapping from the purpose of a color (like `highlightedBorderColor` or `codeBlockBackgroundColor`) to CSS color values. In that case `replaceColor` would just be an object and `gatsby-remark-vscode` would merge that object with the one defined by the theme internally:
```js
colors = { ...themeColors, ...userColors }
```

Of course, I can see that in many cases you probably _want_ to revisit your color replacements every time you change the theme so maybe this isn't such a good suggestion. Anyway, thanks for clearing this up!
