### ISSUE TITLE
Will this plugin work with gatsby-remark-embed-gist

### ISSUE THREAD

**Issue by chivandikwa** [andrewbranch/gatsby-remark-vscode#26]
Will this great plugin 😄 work with gatsby-remark-embed-gist to highlight the code embedded fro m a gist? I have failed to get this to work and I am unsure If my configuration is wrong or this is not supported.

**Comment by andrewbranch** [comment]
That's not supported, sorry. The reason is that gatsby-remark-embed-gist generates an HTML node, already highlighted and wrapped in HTML tags. gatsby-remark-vscode needs a plain-text code node as an input. You could fairly easily write a plugin or an option for gatsby-remark-embed-gist that would support emitting a code fence rather than an HTML block, and then it would work 🙂
