### ISSUE TITLE
Targeting code not working

### ISSUE THREAD

**Issue by Dajamante** [andrewbranch/gatsby-remark-vscode#48]
Dear Andrew, 
There appear to be no way to target comments.
None of this is working: 

```
.vscode-highlight-code .vscode-highlight-line span.mtk3 {
  color: blue;
}
div#gatsby-focus-wrapper span > span.mtk3 {
  color: blue;
}

.mtk3 {
  color: blue;
}

span > .mtk3 {
  color: blue;
}

.dark-default-dark .vscode-highlight-code .vscode-highlight-line span.mtk3 {
  color: blue;
}
```

**Comment by andrewbranch** [comment]
I would recommend using the `replaceColor` function rather than relying on `.mtk` class names since those could change with an update to your theme. If that doesn’t provide the granularity you need, you could write or adapt your own theme. That said, there’s nothing magic about the HTML generated by this plugin, so if your CSS isn’t working, there’s something wrong with your CSS 😬

**Comment by Dajamante** [comment]
It's still a bit magic to me 😬!
How do I use replaceColor?
I looked at the docs:
```           
replaceColor: x => x,   // Function allowing replacement of a theme color with another. Useful for replacing hex colors with CSS variables.
```
I really don't know how and where I should do it.
Thank you again!

**Comment by Dajamante** [comment]
Thank you. Is this bit CSS? Can you please link an example to show how it is done? Also, if you have an example with code highlighting, I still did not figure out this one. I tried to put the CSS in the module.index.css file that both blog-post.js and index.js use, without luck!
