### ISSUE TITLE
Is it possible to parse a normal string?

### ISSUE THREAD

**Issue by mxmzb** [andrewbranch/gatsby-remark-vscode#59]
can i reuse some library or component from this plugin to run over a normal string, thereby syntax highlighting something in an actual gatsby component? something like https://github.com/conorhastings/react-syntax-highlighter ? 

just asking out of curiosity, would save me from adding just another npm package and growing my assets size (and would potentially prevent code highlighting styles to differ).

**Comment by andrewbranch** [comment]
If I understand you correctly, #53 is designed with this scenario in mind. My current plan is to fix/implement #57 first, then ship a v2.0.0 that includes a preview/alpha of #53, try it on my own blog, and gather feedback. I can’t promise a timeline since this is just a side project for me, but it’s very high on my priority list and I hope to finish it soon.

**Comment by mxmzb** [comment]
yeah, https://github.com/andrewbranch/gatsby-remark-vscode/blob/aa9bda82a0127cb7d87f4c2f9a1608c8a05066c6/examples/example-site/src/templates/react-blog-post.js looks kind of for what i am looking. still bit of boilerplate imho but i don't want to be picky.

thanks for the outlook on your roadmap and thank you so much for your time and effort doing this, i sincerely appreciate it!! 🙏🙏🙏

**Comment by andrewbranch** [comment]
This is well underway in v2! There’s a GraphQL resolver that can be called with raw source text.

<img width="1879" alt="image" src="https://user-images.githubusercontent.com/3277153/73087164-f11d7200-3e86-11ea-9887-fcda81b99dc7.png">
