### ISSUE TITLE
Add an explicit dependency to ‘request’

### ISSUE THREAD

**Issue by leafac** [andrewbranch/gatsby-remark-vscode#72]
This plugin [requires `request`](https://github.com/andrewbranch/gatsby-remark-vscode/blob/7a6c8db8154f7c3832b5fa2476be09ea58908fca/src/host.js#L2), which [isn’t listed as a direct dependency](https://github.com/andrewbranch/gatsby-remark-vscode/blob/7a6c8db8154f7c3832b5fa2476be09ea58908fca/package.json#L33-L65). In many cases, that could be okay, because `request` would be an indirect dependency (a dependency of a dependency), and it would be available anyway. But for some reason when I was testing `request` wasn’t there, and I had to install it manually.

What do you think about adding `request` as a direct dependency (adding it on `package.json`)?

**Comment by andrewbranch** [comment]
You’re right, it’s a total mistake; it definitely should be in package.json—however, I’ve removed `request` in v2 (see #64) which I’m planning to release this weekend, so I probably won’t do an extra release of v1 just for that. (Because of the issues described in #67, I’m not planning to support v1 once v2 is released.)

**Comment by leafac** [comment]
Sounds good. Let’s close this, then.
