### ISSUE TITLE
Usage without gatsby

### ISSUE THREAD

**Issue by codepunkt** [andrewbranch/gatsby-remark-vscode#99]
I'm not sure about the differences between remark-plugins and gatsby-remark-plugins. However, other frameworks also start to use mdx, specifically Vue and in react-land, Next.js.

They support remark and rehype plugins, but not gatsby-remark-plugins. Would this be possible as "just"a remark plugin?

**Comment by andrewbranch** [comment]
Short answer: yes, it should be possible to extract or to move the non-gatsby functionality out. Short question: wanna help? 😄

**Comment by codepunkt** [comment]
Sure. How?

I'm not sure what most of the code is doing in the first place 😞

**Comment by andrewbranch** [comment]
That might be an obstacle 😄 

Snark aside, my point was just that I think this is a good idea, and I saw your tweets and it looked like you might have been doing some good investigations in this space. So if you felt like it was something you wanted to work on, I’d be on board. But currently, this isn’t on my personal roadmap for this plugin. If more people become interested in it, that could certainly change.

**Comment by codepunkt** [comment]
I would like to work on it. However, i fail to understand a lot of things - for example how Gatsby's GraphQL stuff is at all related to this plugin. If you'd like to jump on a Zoom call, we can certainly talk about that and maybe you can give me a broad overview/short walkthrough so that i can join the dots.

**Comment by andrewbranch** [comment]
Sure! I’m in Pacific time in the US and work approximately a standard 9–5, so I imagine that makes the weekend a better bet for you, but let me know a time slot or two that works for you and we can set something up. Feel free to DM me on Twitter if that’s easier.

**Comment by elviswolcott** [comment]
I'm in the process of writing a standalone module that extracts out over at [elviswolcott/vscode-highlight](https://github.com/elviswolcott/vscode-highlight).

It's strongly inspired by the work done on this repo (it's the best example of how to use vscode-textmate I could find). 
So far, I've got the basic highlighting stuff working and the ability to spit out (unoptomized) HTML or the data as JSON.

As I write this I'm in the middle of a rewrite to clean up how it handles the extension data and clean it all up before I publish a v1 to npm. The current data handling approach has some issues (e.g. HTML doesn't get highlighted correctly) but the fix is relatively simple once I clean it all up. It's pretty simple once you rip out all the Gatsby/GraphQL stuff.

Feel free to take inspiration from/borrow/contribute if it seems like what you're looking for.

**Comment by andrewbranch** [comment]
Cool, thanks! Can you give me an example of HTML not getting highlighted correctly? I’ve believed that there could be discrepancies in the results between my plugin and VS Code itself, but haven’t gone out of my way to find them. But I am interested in it being 100% accurate, so these are my favorite kind of bug reports.

**Comment by elviswolcott** [comment]
The bug is in my implementation. I'm not handling the case where multiple grammars have the language I believe.

**Comment by andrewbranch** [comment]
Oh gotcha, I misunderstood what you meant by “current.”

**Comment by elviswolcott** [comment]
Revisiting my attempt at this after being busy at work for a few weeks.
I've dug around a bit and am running into a weird issue where my implementation can't highlight HTML (plain, embedded in MD, or in code blocks).

https://codepen.io/ElvisWolcott/pen/ZEQwOro
The pen shows the generated HTML and the markdown source is commented in the JS pane.

I think it has something to do with how I'm multiple grammars or language definitions with the same id maybe?
I've dug around and determined it's using the scope `text.html.derivative` which seems to be wrong, but I'm not sure where in the process I'm setting up the data incorrectly.

**Comment by mxmzb** [comment]
Would it make sense to just transform some markdown (or just the `<code>` tags of some markdown string) into AST and pass it to some function of `gatsby-remark-vscode` as a quick solution?

**Comment by janosh** [comment]
Very cool to see this conversation.

@elviswolcott Thanks for kicking this off. Anything you need help with? I'd also be interested in a standalone module as I've recently started using Svelte + Snowpack. The best options currently available in that ecosystem seem to be PrismJS and highlight.js. Not to slight them, but neither of those can hold a candle to `gatsby-remark-vscode` in terms of output quality.

**Comment by wooorm** [comment]
Hi all! I’m coming to this conversation as the maintainer of remark et al, and would also like to see a standalone project, for example so that it can be used directly with remark, but also for example with [Next](https://nextjs.org), or [MDSveX](https://github.com/pngwn/MDsveX).

I think architecturally there would be:

* just highlighting, which @elviswolcott was working on
* remark plugin, which I can help with
* the glue to make it work in Gatsby

For the remark part, there are certain Gatsby-esque things in this project, such as that an `html` node is injected: https://github.com/andrewbranch/gatsby-remark-vscode/blob/fad5dd3a17ae48dc6b5fe8f30bb86cc9f5100279/src/index.js#L200-L201
That works fine if you’re indeed going to make HTML, and Gatsby (and MDX@1) are doing some magic there, but with MDX@2 we’re going remove it in favor of an AST: [hast](https://github.com/syntax-tree/hast) ([rehype](https://github.com/rehypejs/rehype)) (which the other stuff made on remark already supports).

Anyway: I’ve got enough on my plate that I can’t help with the highlighting (although: I don‘t have vscode experience but have made [lowlight](https://github.com/wooorm/lowlight)/[refractor](https://github.com/wooorm/refractor)) or the Gatsby side, but I can take care of the remark side!

**Comment by codepunkt** [comment]
@elviswolcott Any news on this? I'll also try to get this working for @wilsonjs

**Comment by codepunkt** [comment]
I've got a very rough prototype working for @wilsonjs - I copied over the code file by file to get a better understanding and basically mostly altered the `src / index.js`.

https://github.com/wilsonjs/wilson/tree/syntax-highlight

Will now fork and try to get it working based on this repo because I'd rather not maintain all the stuff that I copied around and tried to understand over the last 2 days.

**Comment by codepunkt** [comment]
@andrewbranch Care to have a look at the PR? Would love your feedback!

**Comment by wooorm** [comment]
@codepunkt It is allowed. It is supported in some places. To explain why it isn’t always supported, it might be good to think about how the following would work:
Say we’d want to turn markdown into React nodes. And the markdown includes strings of HTML. (How) can React deal with those strings of HTML?
An alternate example for MDX: we have some markdown and some JS(X) as an AST, and a plugin injects some HTML. We want to compile to a JS file. How to deal with that string of HTML?

When possible, instead of injecting a string of HTML into an AST, inject actual AST nodes. This can be done when working on hast (html) nodes by injecting more hast nodes, or on mdast (markdown) nodes [like so](https://github.com/syntax-tree/mdast-util-to-hast#examples). 

This would also make some of your code much easier to reason about. You have a lot of [code that generates a string of HTML](https://github.com/wilsonjs/wilson/blob/56906ea8aaad79b0cc0edbc705fc901a09fd6c5f/packages/remark-vscode/src/renderers/html.js). You’re juggling how to escape attributes there. If you‘d instead return an AST, you don’t have to deal with all that escaping, you support React/JSX/MDX out of the box, and everything becomes faster because you’re not going objects -> string -> objects
